version: "3"
services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ig-api
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    container_name: cache
    image: "redis:7-alpine"
    restart: always
    ports:
      - "6378:6379"
    volumes: 
      - cache:/data
  api:
    container_name: api
    build: .
    command: bash -c "rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/api"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: ig-api
      DB_USER: appuser
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_NAMESPACE: cache
volumes:
  cache:
  data:
  
